### ISSUE TITLE
capacitor plugin migrations fail due to workspace.json missing

### ISSUE THREAD

**Issue by fncap** [nxtend-team/nxtend#397]
Hi, 
in my NX repo, I have angular.json instead of workspace.json
If I run migration, script fail due to missing workspace.json
It is my fault?
In one of my earlier version of my repo, I had workspace.json, after starting from scratch with a new version of NX, only angular.json is present in source code.
What I'm wrong?

**Comment by fncap** [comment]
Little update:
I'm trying to rename angular.json to workspace.json, migration still fail due following error:

Running migration update-workspace-json-11.0.0
Cannot create property 'cmd' on string 'android'
error Command failed with exit code 1.

**Comment by devinshoemaker** [comment]
Hey @fncap, thanks for reporting this. I believe the original workspace error you received is an oversight on my part. I should be able to support both angular and workspace json files with this project. That being said, renaming your angular.json to workspace.json should work, but it looks like you're receiving an error from 11.0.0 which should be fixed in 11.0.1. Can you tell me the exact command that you used for the migration? Also, if you just want to wait for a bit, I can probably push out an update to support angular.json in upgrades. Sorry for the inconvenience.

**Comment by devinshoemaker** [comment]
This has been fixed and will be released with 11.0.2 which I plan to release tonight or tomorrow morning.

**Comment by devinshoemaker** [comment]
@fncap 11.0.2 is published. I would try and reset your project back to an `angular.json` (as long as you want to keep that of course) and then run `ng update @nxtend/capacitor@11.0.2`.

**Comment by fncap** [comment]
@devinshoemaker thanks for your time! 
I'll give it a try asap!
