### ISSUE TITLE
How to Create Ionic Page in a library?

### ISSUE THREAD

**Issue by SynergyEvolved** [nxtend-team/nxtend#627]
Hi there!

When I try to create a page using nx generate @nxtend/ionic-angular:page it wants to create the page in the apps folder.  

I thought that everything in NX should be in libraries.  How do you create a page in a library?

Thanks

-Page

**Comment by WhatsThatItsPat** [comment]
I've had the same issue and I have to do something like this.

I go to the VS Code file explorer and `Copy Relative Path` of the lib in which I want the new page to exist.

I paste that into `directory` and then go up four directories in front of that with `../../../../`.

This gets it close enough. I still usually move the contents of the created folder into its parent because there's no `--flat` option, and then delete the empty folder.

<img width="1142" alt="create-page-in-library" src="https://user-images.githubusercontent.com/764290/167220335-66ad9380-49b7-48ea-bb18-f0b3b7eff7b8.png">

**Comment by SynergyEvolved** [comment]
Thanks!  I ended up creating a library and then a page or component using the your path trick :)

**Comment by WhatsThatItsPat** [comment]
Glad it helped, but you could still leave the issue open because it would be nice if the generator worked a bit better.
